### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException ao invocar BaseWebViewFragment.isInternetConnectionAvailable()

### ISSUE THREAD

**Issue by filipebezerra** [filipebezerra/HorariosRmtcGoiania#103]
Exceção reportada pelos canais Play Store e Fabric:

1. Play Store
  * Total de relatórios: 2
  * Último relatório: 17/01/2016, 08:35
  * Versão 11
  * Android 5.0 e 5.1
  * Galaxy Note3 (hlte), Moto G (falcon_umtsds)
  * Stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'net.i2p.android.ext.floatingactionbutton.FloatingActionsMenu mx.x10.filipebezerra.horariosrmtcgoiania.activities.BaseActivity.getFabMenu()' on a null object reference
	at mx.x10.filipebezerra.horariosrmtcgoiania.fragments.BaseWebViewFragment.isInternetConnectionAvailable(BaseWebViewFragment.java:354)
	at mx.x10.filipebezerra.horariosrmtcgoiania.fragments.BaseWebViewFragment$CustomWebViewClient.onPageStarted(BaseWebViewFragment.java:85)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:534)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:107)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

2. Fabric (Crashlytics)
  * 472 crashes
  * 315 usuários afetados
  * Falha reportada entre 10 e 17/01/2016
  * Stacktrace

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'net.i2p.android.ext.floatingactionbutton.FloatingActionsMenu mx.x10.filipebezerra.horariosrmtcgoiania.activities.BaseActivity.getFabMenu()' on a null object reference
       at mx.x10.filipebezerra.horariosrmtcgoiania.fragments.BaseWebViewFragment.isInternetConnectionAvailable(BaseWebViewFragment.java:354)
       at mx.x10.filipebezerra.horariosrmtcgoiania.fragments.BaseWebViewFragment$CustomWebViewClient.onPageStarted(BaseWebViewFragment.java:85)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:499)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:144)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by filipebezerra** [comment]
Fabric issue ref: https://www.fabric.io/filipebzerras/android/apps/mx.x10.filipebezerra.horariosrmtcgoiania/issues/56929029f5d3a7f76bfbf694
